import { createContext, useContext, useState, type ReactNode } from 'react'

export type Lang = 'en' | 'hi' | 'gu' | 'bn'

export const LANG_LABELS: Record<Lang, string> = {
  en: 'EN',
  hi: 'हिं',
  gu: 'ગુ',
  bn: 'বাং',
}

export const LANG_FULL_NAMES: Record<Lang, string> = {
  en: 'English',
  hi: 'हिन्दी',
  gu: 'ગુજરાતી',
  bn: 'বাংলা',
}

interface LangContextValue {
  lang: Lang
  setLang: (lang: Lang) => void
  toggle: () => void
  t: (key: string) => string
}

const LangContext = createContext<LangContextValue>({
  lang: 'en',
  setLang: () => {},
  toggle: () => {},
  t: (k) => k,
})

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const stored = localStorage.getItem('lang') as Lang
    if (stored && ['en', 'hi', 'gu', 'bn'].includes(stored)) return stored
    return 'en'
  })

  const setLang = (next: Lang) => {
    localStorage.setItem('lang', next)
    setLangState(next)
  }

  const toggle = () => {
    const order: Lang[] = ['en', 'hi', 'gu', 'bn']
    const idx = order.indexOf(lang)
    setLang(order[(idx + 1) % order.length])
  }

  const t = (key: string): string => {
    const dict = DICTIONARIES[lang]
    return dict[key] ?? en[key] ?? key
  }

  return (
    <LangContext.Provider value={{ lang, setLang, toggle, t }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}

// ─── English ──────────────────────────────────────────────────────────
const en: Record<string, string> = {
  // Auth
  'auth.title':           'Field Force Intelligence',
  'auth.subtitle':        'Syngenta Field Force Intelligence',
  'auth.tab.password':    'Email / Password',
  'auth.tab.otp':         'Phone OTP',
  'auth.email':           'Email or Phone',
  'auth.password':        'Password',
  'auth.signin':          'Sign in',
  'auth.signing_in':      'Signing in...',
  'auth.phone':           'Phone Number',
  'auth.send_otp':        'Send OTP',
  'auth.sending_otp':     'Sending OTP...',
  'auth.enter_otp':       'Enter OTP',
  'auth.verify_otp':      'Verify OTP',
  'auth.verifying':       'Verifying...',
  'auth.register':        'Register with password',
  'auth.new_account':     'New account?',
  'auth.demo':            'Demo credentials',
  // Register
  'register.title':       'Create Account',
  'register.name':        'Full Name',
  'register.email':       'Email',
  'register.phone':       'Phone (optional)',
  'register.password':    'Password',
  'register.confirm':     'Confirm Password',
  'register.submit':      'Create Account',
  'register.creating':    'Creating account...',
  'register.login':       'Sign in',
  'register.have_account':'Already have an account?',
  // Nav
  'nav.priorities':       'Priorities',
  'nav.alerts':           'Alerts',
  'nav.devices':          'Devices',
  'nav.overview':         'Overview',
  'nav.reps':             'Reps',
  'nav.signout':          'Sign out',
  // Today
  'today.greeting':       'Good morning',
  'today.growers_ranked': 'growers ranked by visit priority score',
  'today.loading':        'Loading your priorities...',
  'today.none':           'No priorities for today.',
  'today.high_priority':  'High Priority',
  'today.alerts':         'Alerts',
  'today.total':          'Total',
  'today.retry':          'Retry',
  'today.all_done':       'All caught up!',
  'today.no_growers':     'No growers to visit today.',
  // Grower
  'grower.ai_brief':      'AI Visit Brief',
  'grower.actions':       'Recommended Actions',
  'grower.log_outcome':   'Log Visit Outcome',
  'grower.log_another':   'Log Another Outcome',
  'grower.logged':        'Outcome logged',
  'grower.will_sync':     'Will sync automatically when connected.',
  'grower.go_back':       'Go Back',
  // Outcome
  'outcome.logging_for':  'Logging outcome for',
  'outcome.rating':       'Visit Rating',
  'outcome.outcome':      'Outcome',
  'outcome.actions':      'Actions Taken',
  'outcome.notes':        'Notes',
  'outcome.notes_ph':     'Add visit notes, observations...',
  'outcome.save':         'Save Outcome',
  'outcome.saving':       'Saving...',
  'outcome.cancel':       'Cancel',
  'outcome.sale':         'Sale Completed',
  'outcome.follow_up':    'Follow-up Needed',
  'outcome.no_interest':  'No Interest',
  'outcome.complaint':    'Complaint Raised',
  'outcome.rating_err':   'Please select a rating.',
  'outcome.rate_1':       'Very poor',
  'outcome.rate_2':       'Poor',
  'outcome.rate_3':       'Average',
  'outcome.rate_4':       'Good',
  'outcome.rate_5':       'Excellent',
  // Anomalies
  'anomaly.title':        'Anomaly Alerts',
  'anomaly.detected':     'anomalies detected across your territory',
  'anomaly.scanning':     'Scanning for anomalies...',
  'anomaly.none':         'No anomalies detected',
  'anomaly.all':          'All',
  'anomaly.high':         'High',
  'anomaly.medium':       'Medium',
  'anomaly.low':          'Low',
  'anomaly.no_filter':    'No anomalies for this filter.',
  // Devices
  'devices.title':        'Your Devices',
  'devices.subtitle':     "Devices logged into your account. Revoke any you don't recognize.",
  'devices.current_id':   'Current device ID',
  'devices.this_device':  'This device',
  'devices.revoke':       'Revoke',
  'devices.revoke_confirm': 'Revoke this device? It will be signed out.',
  // Manager overview
  'manager.overview':     'Territory Overview',
  'manager.health':       'Territory Health',
  'manager.healthy':      'Healthy',
  'manager.moderate':     'Moderate',
  'manager.at_risk':      'At Risk',
  'manager.total_reps':   'Total Reps',
  'manager.growers':      'Growers',
  'manager.outcomes_30d': 'Outcomes (30d)',
  'manager.avg_rating':   'Avg Rating',
  'manager.high_priority':'High Priority',
  'manager.top_priorities':'Top Priorities Across Territory',
  'manager.view_all':     'View all reps →',
  // Reps list
  'reps.title':           'Field Representatives',
  'reps.in_territory':    'reps in your territory',
  'reps.excellent':       'Excellent',
  'reps.total':           'Total',
  'reps.at_risk':         'At Risk',
  'reps.sort_by':         'Sort by',
  'reps.outcomes':        'Outcomes',
  'reps.rating':          'Rating',
  'reps.name':            'Name',
  'reps.growers':         'Growers',
  'reps.outcomes_30d':    'Outcomes (30d)',
  'reps.avg_rating':      'Avg Rating',
  'reps.none':            'No reps found.',
  'reps.perf_excellent':  'Excellent',
  'reps.perf_good':       'Good',
  'reps.perf_attention':  'Needs Attention',
  // Rep detail
  'rep.priorities':       'Priorities',
  'rep.outcomes':         'Outcomes',
  'rep.anomalies':        'Anomalies',
  'rep.no_priorities':    'No priorities assigned.',
  'rep.no_outcomes':      'No recent outcomes.',
  'rep.no_anomalies':     'No anomalies for this rep.',
  // Sync
  'sync.pending':         'pending',
  'sync.now':             'Sync now',
  // Time
  'time.just_now':        'Just now',
  'time.ago':             'ago',
  'time.active_now':      'Active now',
  // Language
  'lang.label':           'Language',
  // NBA action codes (from backend nba_engine.py)
  'nba.complaint_resolution':     'Resolve open complaint',
  'nba.pest_advisory':            'Pest advisory',
  'nba.inventory_replenishment':  'Replenish inventory',
  'nba.seed_recommendation':      'Recommend seeds',
  'nba.relationship_maintenance': 'Relationship check-in',
  'nba.competitor_retention':     'Competitor retention',

  // Outcome form action chips (display labels only — values stay English for DB)
  'action.demonstrated_product':  'Demonstrated product',
  'action.shared_brochure':       'Shared brochure',
  'action.collected_soil_sample': 'Collected soil sample',
  'action.discussed_crop_plan':   'Discussed crop plan',
  'action.resolved_complaint':    'Resolved complaint',
  'action.offered_trial_pack':    'Offered trial pack',
  'action.scheduled_follow_up':   'Scheduled follow-up',
  'action.processed_order':       'Processed order',
  // Reason codes (from backend explainer.py)
  'reason.pest_critical':         'Critical pest outbreak — crop at risk',
  'reason.pest_alert':            'Pest alert — monitor closely',
  'reason.inventory_critical':    'Inventory critically low — stockout imminent',
  'reason.inventory_low':         'Inventory running low — reorder needed',
  'reason.visit_overdue_21':      'Overdue visit — not contacted in 21+ days',
  'reason.visit_due_14':          'Visit recommended — not contacted in 14+ days',
  'reason.complaint_open':        'Open complaint requires immediate resolution',
  'reason.competitor_spotted':    'Competitor activity spotted — retention risk',
  'reason.weather_high_risk':     'High weather risk — crop may need urgent attention',
  'reason.crop_stage_critical':   'Critical crop stage — high recommendation receptivity',

  // Anomaly codes (from backend anomaly_detector.py)
  'anomaly.stock_critically_low': 'Stock below 10% — risk of stockout within 3 days',
  'anomaly.visit_gap_exceeded':   'No visit in 3+ weeks during active crop season',
  'anomaly.competitor_spotted':   'Competitor activity reported in this area',
  'anomaly.complaint_unresolved': 'Open complaint requires immediate resolution',

  // PriorityCard pluralization
  'priority.alert_one':           'alert',
  'priority.alert_many':          'alerts',
  // Override-rule codes (from backend override_rules.py)
  'override.complaint_immediate':   'Open complaint requires immediate visit',
  'override.pest_outbreak_region':  'Critical pest outbreak in region',
  'override.visit_overdue_30':      'Overdue visit — last contact over 30 days ago',
  // Learning Trail (manager weights history page)
  'trail.title':                'Learning Trail',
  'trail.how_learns':           'How the model learns',
  'trail.intro':                'Each time an outcome is logged, signal weights are recalculated. This trail shows every adjustment — which signals gained importance, which lost it, and what triggered the change.',
  'trail.back_to_overview':     '← Back to Overview',
  'trail.outcome_label':        'Outcome',
  'trail.logged_suffix':        'logged',
  'trail.manual_recalibration': 'Manual recalibration',
  'trail.signals_shifted':      'signals shifted',
  'trail.what_changed':         'What changed',
  'trail.all_weights':          'All weights at this point',
  'trail.empty':                'No weight changes recorded yet.',

  // Signal labels (used in Learning Trail)
  'signal.pest_alert':          'Pest Alert',
  'signal.inventory_shortage':  'Inventory Shortage',
  'signal.days_since_visit':    'Days Since Visit',
  'signal.weather_risk':        'Weather Risk',
  'signal.complaint_open':      'Open Complaint',
  'signal.crop_stage':          'Crop Stage',
  'signal.revenue_potential':   'Revenue Potential',
  'signal.competitor_activity': 'Competitor Activity',
  'reason.ndvi_high_stress':     'Satellite shows severe crop stress',
  'reason.ndvi_moderate_stress': 'Satellite shows moderate crop stress',
  // Grower detail data source widgets
  'widget.satellite_title':    'Satellite Crop Health',
  'widget.pest_title':         'Regional Pest Advisory',
  'widget.scene_date':         'Scene date',
  'widget.cloud_cover':        'Cloud cover',
  'widget.source':             'Source',
  'widget.stress_score':       'Stress score',
  'widget.severity':           'Severity',
  'widget.district':           'District',
  'widget.live':               'Live',
  'widget.baseline':           'Baseline',
  'widget.unavailable':        'Data unavailable',
  'widget.loading':            'Loading...',
  'auth.2fa.sent_to':       'Verification code sent to',
  'auth.2fa.use_different':  'Use a different account',
  'auth.2fa.enter_code':     'Enter 6-digit code',
  'auth.2fa.verify':         'Verify and sign in',
  'auth.2fa.verifying':      'Verifying...',
  'auth.2fa.dev_hint':       'DEV MODE — code:',
}

// ─── Hindi (from Kunal's PR, retained verbatim) ─────────────────────
const hi: Record<string, string> = {
  'auth.title':           'फील्ड फोर्स इंटेलिजेंस',
  'auth.subtitle':        'सिंजेंटा फील्ड फोर्स इंटेलिजेंस',
  'auth.tab.password':    'ईमेल / पासवर्ड',
  'auth.tab.otp':         'फोन OTP',
  'auth.email':           'ईमेल या फोन',
  'auth.password':        'पासवर्ड',
  'auth.signin':          'साइन इन करें',
  'auth.signing_in':      'साइन इन हो रहा है...',
  'auth.phone':           'फोन नंबर',
  'auth.send_otp':        'OTP भेजें',
  'auth.sending_otp':     'OTP भेजा जा रहा है...',
  'auth.enter_otp':       'OTP दर्ज करें',
  'auth.verify_otp':      'OTP सत्यापित करें',
  'auth.verifying':       'सत्यापन हो रहा है...',
  'auth.register':        'पासवर्ड से रजिस्टर करें',
  'auth.new_account':     'नया खाता?',
  'auth.demo':            'डेमो क्रेडेंशियल',
  'register.title':       'खाता बनाएं',
  'register.name':        'पूरा नाम',
  'register.email':       'ईमेल',
  'register.phone':       'फोन (वैकल्पिक)',
  'register.password':    'पासवर्ड',
  'register.confirm':     'पासवर्ड की पुष्टि करें',
  'register.submit':      'खाता बनाएं',
  'register.creating':    'खाता बन रहा है...',
  'register.login':       'साइन इन करें',
  'register.have_account':'पहले से खाता है?',
  'nav.priorities':       'प्राथमिकताएं',
  'nav.alerts':           'अलर्ट',
  'nav.devices':          'डिवाइस',
  'nav.overview':         'अवलोकन',
  'nav.reps':             'प्रतिनिधि',
  'nav.signout':          'साइन आउट',
  'today.greeting':       'नमस्ते',
  'today.growers_ranked': 'किसान विज़िट प्राथमिकता के अनुसार क्रमबद्ध',
  'today.loading':        'प्राथमिकताएं लोड हो रही हैं...',
  'today.none':           'आज कोई प्राथमिकता नहीं।',
  'today.high_priority':  'उच्च प्राथमिकता',
  'today.alerts':         'अलर्ट',
  'today.total':          'कुल',
  'today.retry':          'पुनः प्रयास',
  'today.all_done':       'सब ठीक है!',
  'today.no_growers':     'आज कोई किसान नहीं मिलना है।',
  'grower.ai_brief':      'AI विज़िट सारांश',
  'grower.actions':       'अनुशंसित कार्रवाइयां',
  'grower.log_outcome':   'विज़िट परिणाम दर्ज करें',
  'grower.log_another':   'और परिणाम दर्ज करें',
  'grower.logged':        'परिणाम दर्ज हो गया',
  'grower.will_sync':     'कनेक्ट होने पर स्वचालित रूप से सिंक होगा।',
  'grower.go_back':       'वापस जाएं',
  'outcome.logging_for':  'के लिए परिणाम दर्ज करना',
  'outcome.rating':       'विज़िट रेटिंग',
  'outcome.outcome':      'परिणाम',
  'outcome.actions':      'की गई कार्रवाइयां',
  'outcome.notes':        'नोट्स',
  'outcome.notes_ph':     'विज़िट नोट्स, टिप्पणियां...',
  'outcome.save':         'परिणाम सहेजें',
  'outcome.saving':       'सहेजा जा रहा है...',
  'outcome.cancel':       'रद्द करें',
  'outcome.sale':         'बिक्री पूर्ण',
  'outcome.follow_up':    'फॉलो-अप ज़रूरी',
  'outcome.no_interest':  'कोई रुचि नहीं',
  'outcome.complaint':    'शिकायत दर्ज',
  'outcome.rating_err':   'कृपया रेटिंग चुनें।',
  'outcome.rate_1':       'बहुत खराब',
  'outcome.rate_2':       'खराब',
  'outcome.rate_3':       'ठीक है',
  'outcome.rate_4':       'अच्छा',
  'outcome.rate_5':       'बहुत अच्छा',
  'anomaly.title':        'असामान्य अलर्ट',
  'anomaly.detected':     'आपके क्षेत्र में असामान्यताएं मिलीं',
  'anomaly.scanning':     'असामान्यताएं खोजी जा रही हैं...',
  'anomaly.none':         'कोई असामान्यता नहीं मिली',
  'anomaly.all':          'सभी',
  'anomaly.high':         'उच्च',
  'anomaly.medium':       'मध्यम',
  'anomaly.low':          'निम्न',
  'anomaly.no_filter':    'इस फ़िल्टर के लिए कोई अलर्ट नहीं।',
  'devices.title':        'आपके डिवाइस',
  'devices.subtitle':     'आपके खाते में लॉग इन डिवाइस। अपरिचित को रद्द करें।',
  'devices.current_id':   'वर्तमान डिवाइस ID',
  'devices.this_device':  'यह डिवाइस',
  'devices.revoke':       'रद्द करें',
  'devices.revoke_confirm': 'इस डिवाइस को रद्द करें? इसे साइन आउट कर दिया जाएगा।',
  'manager.overview':     'क्षेत्र अवलोकन',
  'manager.health':       'क्षेत्र स्वास्थ्य',
  'manager.healthy':      'स्वस्थ',
  'manager.moderate':     'सामान्य',
  'manager.at_risk':      'खतरे में',
  'manager.total_reps':   'कुल प्रतिनिधि',
  'manager.growers':      'किसान',
  'manager.outcomes_30d': 'परिणाम (30 दिन)',
  'manager.avg_rating':   'औसत रेटिंग',
  'manager.high_priority':'उच्च प्राथमिकता',
  'manager.top_priorities':'क्षेत्र की शीर्ष प्राथमिकताएं',
  'manager.view_all':     'सभी प्रतिनिधि देखें →',
  'reps.title':           'फील्ड प्रतिनिधि',
  'reps.in_territory':    'आपके क्षेत्र में प्रतिनिधि',
  'reps.excellent':       'उत्कृष्ट',
  'reps.total':           'कुल',
  'reps.at_risk':         'ध्यान चाहिए',
  'reps.sort_by':         'क्रमबद्ध करें',
  'reps.outcomes':        'परिणाम',
  'reps.rating':          'रेटिंग',
  'reps.name':            'नाम',
  'reps.growers':         'किसान',
  'reps.outcomes_30d':    'परिणाम (30 दिन)',
  'reps.avg_rating':      'औसत रेटिंग',
  'reps.none':            'कोई प्रतिनिधि नहीं मिला।',
  'reps.perf_excellent':  'उत्कृष्ट',
  'reps.perf_good':       'अच्छा',
  'reps.perf_attention':  'ध्यान चाहिए',
  'rep.priorities':       'प्राथमिकताएं',
  'rep.outcomes':         'परिणाम',
  'rep.anomalies':        'असामान्यताएं',
  'rep.no_priorities':    'कोई प्राथमिकता नहीं।',
  'rep.no_outcomes':      'कोई हालिया परिणाम नहीं।',
  'rep.no_anomalies':     'इस प्रतिनिधि के लिए कोई असामान्यता नहीं।',
  'sync.pending':         'बकाया',
  'sync.now':             'अभी सिंक करें',
  'time.just_now':        'अभी',
  'time.ago':             'पहले',
  'time.active_now':      'अभी सक्रिय',
  'lang.label':           'भाषा',
  'nba.complaint_resolution':     'खुली शिकायत का समाधान करें',
  'nba.pest_advisory':            'कीट सलाह',
  'nba.inventory_replenishment':  'स्टॉक की पुनःपूर्ति',
  'nba.seed_recommendation':      'बीज की सिफारिश',
  'nba.relationship_maintenance': 'संबंध जाँच',
  'nba.competitor_retention':     'प्रतिस्पर्धी से बचाव',

  'action.demonstrated_product':  'उत्पाद का प्रदर्शन',
  'action.shared_brochure':       'ब्रोशर साझा किया',
  'action.collected_soil_sample': 'मिट्टी का नमूना लिया',
  'action.discussed_crop_plan':   'फसल योजना पर चर्चा',
  'action.resolved_complaint':    'शिकायत का समाधान',
  'action.offered_trial_pack':    'ट्रायल पैक दिया',
  'action.scheduled_follow_up':   'फॉलो-अप तय किया',
  'action.processed_order':       'ऑर्डर प्रोसेस किया',
  'reason.pest_critical':         'गंभीर कीट प्रकोप — फसल खतरे में',
  'reason.pest_alert':            'कीट अलर्ट — ध्यान से निगरानी करें',
  'reason.inventory_critical':    'स्टॉक अत्यंत कम — स्टॉकआउट निकट',
  'reason.inventory_low':         'स्टॉक कम हो रहा — पुनः ऑर्डर करें',
  'reason.visit_overdue_21':      'विज़िट बाकी — 21+ दिनों से संपर्क नहीं',
  'reason.visit_due_14':          'विज़िट अनुशंसित — 14+ दिनों से संपर्क नहीं',
  'reason.complaint_open':        'खुली शिकायत — तत्काल समाधान चाहिए',
  'reason.competitor_spotted':    'प्रतिस्पर्धी सक्रिय — संबंध बचाव जरूरी',
  'reason.weather_high_risk':     'मौसम जोखिम अधिक — फसल पर तत्काल ध्यान दें',
  'reason.crop_stage_critical':   'फसल का महत्वपूर्ण चरण — सिफारिशों के लिए उच्च ग्रहणशीलता',

  'anomaly.stock_critically_low': 'स्टॉक 10% से कम — 3 दिनों में स्टॉकआउट का जोखिम',
  'anomaly.visit_gap_exceeded':   '3+ हफ्तों में कोई विज़िट नहीं — सक्रिय फसल सीज़न',
  'anomaly.competitor_spotted':   'इस क्षेत्र में प्रतिस्पर्धी गतिविधि',
  'anomaly.complaint_unresolved': 'खुली शिकायत — तत्काल समाधान चाहिए',

  'priority.alert_one':           'अलर्ट',
  'priority.alert_many':          'अलर्ट',
  'override.complaint_immediate':   'खुली शिकायत — तत्काल विज़िट आवश्यक',
  'override.pest_outbreak_region':  'क्षेत्र में गंभीर कीट प्रकोप',
  'override.visit_overdue_30':      'विज़िट बाकी — 30+ दिनों से संपर्क नहीं',
  'trail.title':                'सीखने का इतिहास',
  'trail.how_learns':           'मॉडल कैसे सीखता है',
  'trail.intro':                'हर बार जब परिणाम दर्ज किया जाता है, सिग्नल भार पुनः गणना किए जाते हैं। यह इतिहास हर समायोजन दिखाता है — कौन से सिग्नल को महत्व मिला, किसका कम हुआ, और परिवर्तन का कारण क्या था।',
  'trail.back_to_overview':     '← अवलोकन पर वापस',
  'trail.outcome_label':        'परिणाम',
  'trail.logged_suffix':        'दर्ज',
  'trail.manual_recalibration': 'मैनुअल पुनर्संरेखण',
  'trail.signals_shifted':      'सिग्नल बदले',
  'trail.what_changed':         'क्या बदला',
  'trail.all_weights':          'इस बिंदु पर सभी भार',
  'trail.empty':                'अभी तक कोई भार परिवर्तन नहीं।',

  'signal.pest_alert':          'कीट अलर्ट',
  'signal.inventory_shortage':  'स्टॉक की कमी',
  'signal.days_since_visit':    'विज़िट के बाद के दिन',
  'signal.weather_risk':        'मौसम जोखिम',
  'signal.complaint_open':      'खुली शिकायत',
  'signal.crop_stage':          'फसल चरण',
  'signal.revenue_potential':   'राजस्व संभावना',
  'signal.competitor_activity': 'प्रतिस्पर्धी गतिविधि',
  'reason.ndvi_high_stress':     'उपग्रह डेटा — गंभीर फसल तनाव',
  'reason.ndvi_moderate_stress': 'उपग्रह डेटा — मध्यम फसल तनाव',
  'widget.satellite_title':    'उपग्रह फसल स्वास्थ्य',
  'widget.pest_title':         'क्षेत्रीय कीट सलाह',
  'widget.scene_date':         'दृश्य तिथि',
  'widget.cloud_cover':        'बादल आवरण',
  'widget.source':             'स्रोत',
  'widget.stress_score':       'तनाव स्कोर',
  'widget.severity':           'गंभीरता',
  'widget.district':           'जिला',
  'widget.live':               'लाइव',
  'widget.baseline':           'आधार रेखा',
  'widget.unavailable':        'डेटा उपलब्ध नहीं',
  'widget.loading':            'लोड हो रहा है...',
  'auth.2fa.sent_to':       'सत्यापन कोड भेजा गया',
  'auth.2fa.use_different':  'अलग खाते का उपयोग करें',
  'auth.2fa.enter_code':     '6-अंकीय कोड दर्ज करें',
  'auth.2fa.verify':         'सत्यापित करें और साइन इन करें',
  'auth.2fa.verifying':      'सत्यापित हो रहा है...',
  'auth.2fa.dev_hint':       'डेव मोड — कोड:',
}

// ─── Gujarati ─────────────────────────────────────────────────────────
const gu: Record<string, string> = {
  'auth.title':           'ફીલ્ડ ફોર્સ ઇન્ટેલિજન્સ',
  'auth.subtitle':        'સિન્જેન્ટા ફીલ્ડ ફોર્સ ઇન્ટેલિજન્સ',
  'auth.tab.password':    'ઇમેઇલ / પાસવર્ડ',
  'auth.tab.otp':         'ફોન OTP',
  'auth.email':           'ઇમેઇલ અથવા ફોન',
  'auth.password':        'પાસવર્ડ',
  'auth.signin':          'સાઇન ઇન કરો',
  'auth.signing_in':      'સાઇન ઇન થઇ રહ્યું છે...',
  'auth.phone':           'ફોન નંબર',
  'auth.send_otp':        'OTP મોકલો',
  'auth.sending_otp':     'OTP મોકલાઇ રહ્યો છે...',
  'auth.enter_otp':       'OTP દાખલ કરો',
  'auth.verify_otp':      'OTP ચકાસો',
  'auth.verifying':       'ચકાસણી થઇ રહી છે...',
  'auth.register':        'પાસવર્ડ સાથે રજિસ્ટર કરો',
  'auth.new_account':     'નવું ખાતું?',
  'auth.demo':            'ડેમો ક્રેડેન્શિયલ',
  'register.title':       'ખાતું બનાવો',
  'register.name':        'પૂરું નામ',
  'register.email':       'ઇમેઇલ',
  'register.phone':       'ફોન (વૈકલ્પિક)',
  'register.password':    'પાસવર્ડ',
  'register.confirm':     'પાસવર્ડની પુષ્ટિ કરો',
  'register.submit':      'ખાતું બનાવો',
  'register.creating':    'ખાતું બની રહ્યું છે...',
  'register.login':       'સાઇન ઇન કરો',
  'register.have_account':'પહેલેથી ખાતું છે?',
  'nav.priorities':       'પ્રાથમિકતાઓ',
  'nav.alerts':           'એલર્ટ',
  'nav.devices':          'ડિવાઇસ',
  'nav.overview':         'અવલોકન',
  'nav.reps':             'પ્રતિનિધિ',
  'nav.signout':          'સાઇન આઉટ',
  'today.greeting':       'સુપ્રભાત',
  'today.growers_ranked': 'મુલાકાત પ્રાથમિકતા અનુસાર ખેડૂતો ક્રમબદ્ધ',
  'today.loading':        'પ્રાથમિકતાઓ લોડ થઇ રહી છે...',
  'today.none':           'આજે કોઇ પ્રાથમિકતા નથી.',
  'today.high_priority':  'ઉચ્ચ પ્રાથમિકતા',
  'today.alerts':         'એલર્ટ',
  'today.total':          'કુલ',
  'today.retry':          'ફરી પ્રયાસ કરો',
  'today.all_done':       'બધું પૂર્ણ!',
  'today.no_growers':     'આજે કોઇ ખેડૂતને મળવાનું નથી.',
  'grower.ai_brief':      'AI મુલાકાત સારાંશ',
  'grower.actions':       'ભલામણ કરેલ ક્રિયાઓ',
  'grower.log_outcome':   'મુલાકાત પરિણામ નોંધો',
  'grower.log_another':   'બીજું પરિણામ નોંધો',
  'grower.logged':        'પરિણામ નોંધાયું',
  'grower.will_sync':     'કનેક્ટ થતાં આપોઆપ સિંક થશે.',
  'grower.go_back':       'પાછા જાઓ',
  'outcome.logging_for':  'માટે પરિણામ નોંધી રહ્યા છીએ',
  'outcome.rating':       'મુલાકાત રેટિંગ',
  'outcome.outcome':      'પરિણામ',
  'outcome.actions':      'કરેલી ક્રિયાઓ',
  'outcome.notes':        'નોંધ',
  'outcome.notes_ph':     'મુલાકાત નોંધ, અવલોકન...',
  'outcome.save':         'પરિણામ સાચવો',
  'outcome.saving':       'સાચવી રહ્યા છીએ...',
  'outcome.cancel':       'રદ કરો',
  'outcome.sale':         'વેચાણ પૂર્ણ',
  'outcome.follow_up':    'ફોલો-અપ જરૂરી',
  'outcome.no_interest':  'કોઇ રસ નથી',
  'outcome.complaint':    'ફરિયાદ નોંધાઇ',
  'outcome.rating_err':   'કૃપા કરી રેટિંગ પસંદ કરો.',
  'outcome.rate_1':       'ખૂબ ખરાબ',
  'outcome.rate_2':       'ખરાબ',
  'outcome.rate_3':       'સામાન્ય',
  'outcome.rate_4':       'સારું',
  'outcome.rate_5':       'ઉત્તમ',
  'anomaly.title':        'અસામાન્ય એલર્ટ',
  'anomaly.detected':     'તમારા વિસ્તારમાં અસામાન્યતા મળી',
  'anomaly.scanning':     'અસામાન્યતા શોધી રહ્યા છીએ...',
  'anomaly.none':         'કોઇ અસામાન્યતા મળી નથી',
  'anomaly.all':          'બધા',
  'anomaly.high':         'ઉચ્ચ',
  'anomaly.medium':       'મધ્યમ',
  'anomaly.low':          'નીચું',
  'anomaly.no_filter':    'આ ફિલ્ટર માટે કોઇ એલર્ટ નથી.',
  'devices.title':        'તમારા ડિવાઇસ',
  'devices.subtitle':     'તમારા ખાતામાં લોગ ઇન ડિવાઇસ. અપરિચિત રદ કરો.',
  'devices.current_id':   'વર્તમાન ડિવાઇસ ID',
  'devices.this_device':  'આ ડિવાઇસ',
  'devices.revoke':       'રદ કરો',
  'devices.revoke_confirm': 'આ ડિવાઇસ રદ કરો? તેને સાઇન આઉટ કરવામાં આવશે.',
  'manager.overview':     'વિસ્તાર અવલોકન',
  'manager.health':       'વિસ્તાર સ્વાસ્થ્ય',
  'manager.healthy':      'સ્વસ્થ',
  'manager.moderate':     'સામાન્ય',
  'manager.at_risk':      'જોખમમાં',
  'manager.total_reps':   'કુલ પ્રતિનિધિ',
  'manager.growers':      'ખેડૂતો',
  'manager.outcomes_30d': 'પરિણામો (30 દિવસ)',
  'manager.avg_rating':   'સરેરાશ રેટિંગ',
  'manager.high_priority':'ઉચ્ચ પ્રાથમિકતા',
  'manager.top_priorities':'વિસ્તારની મુખ્ય પ્રાથમિકતાઓ',
  'manager.view_all':     'બધા પ્રતિનિધિ જુઓ →',
  'reps.title':           'ફીલ્ડ પ્રતિનિધિ',
  'reps.in_territory':    'તમારા વિસ્તારમાં પ્રતિનિધિ',
  'reps.excellent':       'ઉત્તમ',
  'reps.total':           'કુલ',
  'reps.at_risk':         'ધ્યાન આપો',
  'reps.sort_by':         'ક્રમબદ્ધ કરો',
  'reps.outcomes':        'પરિણામો',
  'reps.rating':          'રેટિંગ',
  'reps.name':            'નામ',
  'reps.growers':         'ખેડૂતો',
  'reps.outcomes_30d':    'પરિણામો (30 દિવસ)',
  'reps.avg_rating':      'સરેરાશ રેટિંગ',
  'reps.none':            'કોઇ પ્રતિનિધિ મળ્યા નથી.',
  'reps.perf_excellent':  'ઉત્તમ',
  'reps.perf_good':       'સારું',
  'reps.perf_attention':  'ધ્યાન જરૂરી',
  'rep.priorities':       'પ્રાથમિકતાઓ',
  'rep.outcomes':         'પરિણામો',
  'rep.anomalies':        'અસામાન્યતાઓ',
  'rep.no_priorities':    'કોઇ પ્રાથમિકતા નથી.',
  'rep.no_outcomes':      'કોઇ તાજેતરના પરિણામો નથી.',
  'rep.no_anomalies':     'આ પ્રતિનિધિ માટે કોઇ અસામાન્યતા નથી.',
  'sync.pending':         'બાકી',
  'sync.now':             'હવે સિંક કરો',
  'time.just_now':        'હમણાં',
  'time.ago':             'પહેલા',
  'time.active_now':      'હવે સક્રિય',
  'lang.label':           'ભાષા',
  'nba.complaint_resolution':     'ખુલ્લી ફરિયાદ ઉકેલો',
  'nba.pest_advisory':            'જીવાત સલાહ',
  'nba.inventory_replenishment':  'સ્ટોક ભરપાઇ',
  'nba.seed_recommendation':      'બીજ ભલામણ',
  'nba.relationship_maintenance': 'સંબંધ તપાસ',
  'nba.competitor_retention':     'સ્પર્ધક સામે રક્ષણ',

  'action.demonstrated_product':  'ઉત્પાદન દર્શાવ્યું',
  'action.shared_brochure':       'બ્રોશર શેર કર્યું',
  'action.collected_soil_sample': 'માટીનો નમૂનો લીધો',
  'action.discussed_crop_plan':   'પાક યોજના ચર્ચા',
  'action.resolved_complaint':    'ફરિયાદ ઉકેલી',
  'action.offered_trial_pack':    'ટ્રાયલ પેક આપ્યું',
  'action.scheduled_follow_up':   'ફોલો-અપ નક્કી કર્યું',
  'action.processed_order':       'ઓર્ડર પ્રક્રિયા',
  'reason.pest_critical':         'ગંભીર જીવાત પ્રકોપ — પાક જોખમમાં',
  'reason.pest_alert':            'જીવાત સતર્કતા — નજીકથી દેખરેખ રાખો',
  'reason.inventory_critical':    'સ્ટોક અત્યંત ઓછો — સ્ટોકઆઉટ નજીક',
  'reason.inventory_low':         'સ્ટોક ઓછો થઇ રહ્યો — ફરી ઓર્ડર કરો',
  'reason.visit_overdue_21':      'મુલાકાત બાકી — 21+ દિવસથી સંપર્ક નથી',
  'reason.visit_due_14':          'મુલાકાત ભલામણ — 14+ દિવસથી સંપર્ક નથી',
  'reason.complaint_open':        'ખુલ્લી ફરિયાદ — તાત્કાલિક ઉકેલ જરૂરી',
  'reason.competitor_spotted':    'સ્પર્ધક સક્રિય — સંબંધ સંરક્ષણ જરૂરી',
  'reason.weather_high_risk':     'હવામાન જોખમ વધુ — પાક પર તાત્કાલિક ધ્યાન આપો',
  'reason.crop_stage_critical':   'પાકનો મહત્વનો તબક્કો — ભલામણો માટે ઉચ્ચ ગ્રહણશીલતા',

  'anomaly.stock_critically_low': 'સ્ટોક 10% થી ઓછો — 3 દિવસમાં સ્ટોકઆઉટ જોખમ',
  'anomaly.visit_gap_exceeded':   '3+ અઠવાડિયામાં કોઇ મુલાકાત નથી — સક્રિય પાક સીઝન',
  'anomaly.competitor_spotted':   'આ વિસ્તારમાં સ્પર્ધક પ્રવૃત્તિ',
  'anomaly.complaint_unresolved': 'ખુલ્લી ફરિયાદ — તાત્કાલિક ઉકેલ જરૂરી',

  'priority.alert_one':           'સતર્કતા',
  'priority.alert_many':          'સતર્કતા',
  'override.complaint_immediate':   'ખુલ્લી ફરિયાદ — તાત્કાલિક મુલાકાત જરૂરી',
  'override.pest_outbreak_region':  'વિસ્તારમાં ગંભીર જીવાત પ્રકોપ',
  'override.visit_overdue_30':      'મુલાકાત બાકી — 30+ દિવસથી સંપર્ક નથી',
  'trail.title':                'શીખવાનો ઇતિહાસ',
  'trail.how_learns':           'મોડેલ કેવી રીતે શીખે છે',
  'trail.intro':                'દરેક વખતે જ્યારે પરિણામ નોંધવામાં આવે છે, સિગ્નલ વજન ફરી ગણાય છે. આ ઇતિહાસ દરેક ગોઠવણ બતાવે છે — કયા સિગ્નલને મહત્વ મળ્યું, કોનું ઘટ્યું, અને ફેરફારનું કારણ શું હતું.',
  'trail.back_to_overview':     '← અવલોકન પર પાછા',
  'trail.outcome_label':        'પરિણામ',
  'trail.logged_suffix':        'નોંધાયું',
  'trail.manual_recalibration': 'મેન્યુઅલ પુનઃસંરેખણ',
  'trail.signals_shifted':      'સિગ્નલ બદલાયા',
  'trail.what_changed':         'શું બદલાયું',
  'trail.all_weights':          'આ બિંદુએ બધા વજન',
  'trail.empty':                'હજુ સુધી કોઇ વજન ફેરફાર નથી.',

  'signal.pest_alert':          'જીવાત સતર્કતા',
  'signal.inventory_shortage':  'સ્ટોકની અછત',
  'signal.days_since_visit':    'મુલાકાત પછીના દિવસો',
  'signal.weather_risk':        'હવામાન જોખમ',
  'signal.complaint_open':      'ખુલ્લી ફરિયાદ',
  'signal.crop_stage':          'પાક તબક્કો',
  'signal.revenue_potential':   'આવક સંભાવના',
  'signal.competitor_activity': 'સ્પર્ધક પ્રવૃત્તિ',
  'reason.ndvi_high_stress':     'ઉપગ્રહ ડેટા — ગંભીર પાક તાણ',
  'reason.ndvi_moderate_stress': 'ઉપગ્રહ ડેટા — મધ્યમ પાક તાણ',
  'widget.satellite_title':    'ઉપગ્રહ પાક આરોગ્ય',
  'widget.pest_title':         'પ્રાદેશિક જીવાત સલાહ',
  'widget.scene_date':         'દૃશ્ય તારીખ',
  'widget.cloud_cover':        'વાદળ આવરણ',
  'widget.source':             'સ્ત્રોત',
  'widget.stress_score':       'તાણ સ્કોર',
  'widget.severity':           'ગંભીરતા',
  'widget.district':           'જિલ્લો',
  'widget.live':               'લાઇવ',
  'widget.baseline':           'આધારરેખા',
  'widget.unavailable':        'ડેટા ઉપલબ્ધ નથી',
  'widget.loading':            'લોડ થઈ રહ્યું છે...',
  'auth.2fa.sent_to':       'ચકાસણી કોડ મોકલ્યો',
  'auth.2fa.use_different':  'અલગ ખાતું વાપરો',
  'auth.2fa.enter_code':     '6-અંકનો કોડ દાખલ કરો',
  'auth.2fa.verify':         'ચકાસો અને સાઇન ઇન કરો',
  'auth.2fa.verifying':      'ચકાસી રહ્યું છે...',
  'auth.2fa.dev_hint':       'ડેવ મોડ — કોડ:',
}

// ─── Bengali ──────────────────────────────────────────────────────────
const bn: Record<string, string> = {
  'auth.title':           'ফিল্ড ফোর্স ইন্টেলিজেন্স',
  'auth.subtitle':        'সিনজেন্টা ফিল্ড ফোর্স ইন্টেলিজেন্স',
  'auth.tab.password':    'ইমেইল / পাসওয়ার্ড',
  'auth.tab.otp':         'ফোন OTP',
  'auth.email':           'ইমেইল বা ফোন',
  'auth.password':        'পাসওয়ার্ড',
  'auth.signin':          'সাইন ইন করুন',
  'auth.signing_in':      'সাইন ইন হচ্ছে...',
  'auth.phone':           'ফোন নম্বর',
  'auth.send_otp':        'OTP পাঠান',
  'auth.sending_otp':     'OTP পাঠানো হচ্ছে...',
  'auth.enter_otp':       'OTP লিখুন',
  'auth.verify_otp':      'OTP যাচাই করুন',
  'auth.verifying':       'যাচাই করা হচ্ছে...',
  'auth.register':        'পাসওয়ার্ড দিয়ে নিবন্ধন',
  'auth.new_account':     'নতুন অ্যাকাউন্ট?',
  'auth.demo':            'ডেমো ক্রেডেনশিয়াল',
  'register.title':       'অ্যাকাউন্ট তৈরি করুন',
  'register.name':        'পুরো নাম',
  'register.email':       'ইমেইল',
  'register.phone':       'ফোন (ঐচ্ছিক)',
  'register.password':    'পাসওয়ার্ড',
  'register.confirm':     'পাসওয়ার্ড নিশ্চিত করুন',
  'register.submit':      'অ্যাকাউন্ট তৈরি করুন',
  'register.creating':    'অ্যাকাউন্ট তৈরি হচ্ছে...',
  'register.login':       'সাইন ইন করুন',
  'register.have_account':'ইতিমধ্যে অ্যাকাউন্ট আছে?',
  'nav.priorities':       'অগ্রাধিকার',
  'nav.alerts':           'সতর্কতা',
  'nav.devices':          'ডিভাইস',
  'nav.overview':         'সারসংক্ষেপ',
  'nav.reps':             'প্রতিনিধি',
  'nav.signout':          'সাইন আউট',
  'today.greeting':       'শুভ সকাল',
  'today.growers_ranked': 'ভিজিট অগ্রাধিকার অনুসারে চাষীদের ক্রম',
  'today.loading':        'অগ্রাধিকার লোড হচ্ছে...',
  'today.none':           'আজ কোনো অগ্রাধিকার নেই।',
  'today.high_priority':  'উচ্চ অগ্রাধিকার',
  'today.alerts':         'সতর্কতা',
  'today.total':          'মোট',
  'today.retry':          'পুনরায় চেষ্টা',
  'today.all_done':       'সব সম্পন্ন!',
  'today.no_growers':     'আজ কোনো চাষীর সাথে দেখা করার নেই।',
  'grower.ai_brief':      'AI ভিজিট সারাংশ',
  'grower.actions':       'সুপারিশকৃত পদক্ষেপ',
  'grower.log_outcome':   'ভিজিটের ফলাফল লগ করুন',
  'grower.log_another':   'আরেকটি ফলাফল লগ করুন',
  'grower.logged':        'ফলাফল লগ হয়েছে',
  'grower.will_sync':     'সংযুক্ত হলে স্বয়ংক্রিয়ভাবে সিঙ্ক হবে।',
  'grower.go_back':       'ফিরে যান',
  'outcome.logging_for':  'এর জন্য ফলাফল লগ করা হচ্ছে',
  'outcome.rating':       'ভিজিট রেটিং',
  'outcome.outcome':      'ফলাফল',
  'outcome.actions':      'নেওয়া পদক্ষেপ',
  'outcome.notes':        'নোট',
  'outcome.notes_ph':     'ভিজিট নোট, পর্যবেক্ষণ...',
  'outcome.save':         'ফলাফল সংরক্ষণ',
  'outcome.saving':       'সংরক্ষণ করা হচ্ছে...',
  'outcome.cancel':       'বাতিল',
  'outcome.sale':         'বিক্রয় সম্পন্ন',
  'outcome.follow_up':    'ফলো-আপ প্রয়োজন',
  'outcome.no_interest':  'কোনো আগ্রহ নেই',
  'outcome.complaint':    'অভিযোগ নথিভুক্ত',
  'outcome.rating_err':   'অনুগ্রহ করে একটি রেটিং নির্বাচন করুন।',
  'outcome.rate_1':       'খুব খারাপ',
  'outcome.rate_2':       'খারাপ',
  'outcome.rate_3':       'গড়',
  'outcome.rate_4':       'ভালো',
  'outcome.rate_5':       'চমৎকার',
  'anomaly.title':        'অস্বাভাবিক সতর্কতা',
  'anomaly.detected':     'আপনার এলাকায় অস্বাভাবিকতা পাওয়া গেছে',
  'anomaly.scanning':     'অস্বাভাবিকতা খোঁজা হচ্ছে...',
  'anomaly.none':         'কোনো অস্বাভাবিকতা পাওয়া যায়নি',
  'anomaly.all':          'সব',
  'anomaly.high':         'উচ্চ',
  'anomaly.medium':       'মাঝারি',
  'anomaly.low':          'নিম্ন',
  'anomaly.no_filter':    'এই ফিল্টারের জন্য কোনো সতর্কতা নেই।',
  'devices.title':        'আপনার ডিভাইস',
  'devices.subtitle':     'আপনার অ্যাকাউন্টে লগ ইন ডিভাইস। অপরিচিত যেকোনো বাতিল করুন।',
  'devices.current_id':   'বর্তমান ডিভাইস ID',
  'devices.this_device':  'এই ডিভাইস',
  'devices.revoke':       'বাতিল করুন',
  'devices.revoke_confirm': 'এই ডিভাইস বাতিল করবেন? এটি সাইন আউট হয়ে যাবে।',
  'manager.overview':     'এলাকা সারসংক্ষেপ',
  'manager.health':       'এলাকার স্বাস্থ্য',
  'manager.healthy':      'সুস্থ',
  'manager.moderate':     'মাঝারি',
  'manager.at_risk':      'ঝুঁকিতে',
  'manager.total_reps':   'মোট প্রতিনিধি',
  'manager.growers':      'চাষী',
  'manager.outcomes_30d': 'ফলাফল (30 দিন)',
  'manager.avg_rating':   'গড় রেটিং',
  'manager.high_priority':'উচ্চ অগ্রাধিকার',
  'manager.top_priorities':'এলাকার শীর্ষ অগ্রাধিকার',
  'manager.view_all':     'সব প্রতিনিধি দেখুন →',
  'reps.title':           'ফিল্ড প্রতিনিধি',
  'reps.in_territory':    'আপনার এলাকায় প্রতিনিধি',
  'reps.excellent':       'চমৎকার',
  'reps.total':           'মোট',
  'reps.at_risk':         'মনোযোগ প্রয়োজন',
  'reps.sort_by':         'সাজান',
  'reps.outcomes':        'ফলাফল',
  'reps.rating':          'রেটিং',
  'reps.name':            'নাম',
  'reps.growers':         'চাষী',
  'reps.outcomes_30d':    'ফলাফল (30 দিন)',
  'reps.avg_rating':      'গড় রেটিং',
  'reps.none':            'কোনো প্রতিনিধি পাওয়া যায়নি।',
  'reps.perf_excellent':  'চমৎকার',
  'reps.perf_good':       'ভালো',
  'reps.perf_attention':  'মনোযোগ প্রয়োজন',
  'rep.priorities':       'অগ্রাধিকার',
  'rep.outcomes':         'ফলাফল',
  'rep.anomalies':        'অস্বাভাবিকতা',
  'rep.no_priorities':    'কোনো অগ্রাধিকার বরাদ্দ নেই।',
  'rep.no_outcomes':      'কোনো সাম্প্রতিক ফলাফল নেই।',
  'rep.no_anomalies':     'এই প্রতিনিধির জন্য কোনো অস্বাভাবিকতা নেই।',
  'sync.pending':         'অপেক্ষমান',
  'sync.now':             'এখনই সিঙ্ক করুন',
  'time.just_now':        'এখনই',
  'time.ago':             'আগে',
  'time.active_now':      'এখন সক্রিয়',
  'lang.label':           'ভাষা',
  'nba.complaint_resolution':     'খোলা অভিযোগ সমাধান করুন',
  'nba.pest_advisory':            'কীট পরামর্শ',
  'nba.inventory_replenishment':  'স্টক পুনঃপূরণ',
  'nba.seed_recommendation':      'বীজ সুপারিশ',
  'nba.relationship_maintenance': 'সম্পর্ক পরীক্ষা',
  'nba.competitor_retention':     'প্রতিযোগী থেকে রক্ষা',

  'action.demonstrated_product':  'পণ্য প্রদর্শন',
  'action.shared_brochure':       'ব্রোশার শেয়ার',
  'action.collected_soil_sample': 'মাটির নমুনা সংগ্রহ',
  'action.discussed_crop_plan':   'ফসল পরিকল্পনা আলোচনা',
  'action.resolved_complaint':    'অভিযোগ সমাধান',
  'action.offered_trial_pack':    'ট্রায়াল প্যাক দেওয়া',
  'action.scheduled_follow_up':   'ফলো-আপ নির্ধারণ',
  'action.processed_order':       'অর্ডার প্রক্রিয়া',
  'reason.pest_critical':         'গুরুতর কীট আক্রমণ — ফসল ঝুঁকিতে',
  'reason.pest_alert':            'কীট সতর্কতা — কাছাকাছি নজর রাখুন',
  'reason.inventory_critical':    'স্টক অত্যন্ত কম — স্টকআউট আসন্ন',
  'reason.inventory_low':         'স্টক কম হচ্ছে — পুনঃঅর্ডার দরকার',
  'reason.visit_overdue_21':      'ভিজিট বাকি — 21+ দিন যোগাযোগ নেই',
  'reason.visit_due_14':          'ভিজিট সুপারিশ — 14+ দিন যোগাযোগ নেই',
  'reason.complaint_open':        'খোলা অভিযোগ — অবিলম্বে সমাধান দরকার',
  'reason.competitor_spotted':    'প্রতিযোগী সক্রিয় — সম্পর্ক রক্ষা দরকার',
  'reason.weather_high_risk':     'আবহাওয়া ঝুঁকি বেশি — ফসলে জরুরি মনোযোগ',
  'reason.crop_stage_critical':   'ফসলের গুরুত্বপূর্ণ পর্যায় — সুপারিশের জন্য উচ্চ গ্রহণযোগ্যতা',

  'anomaly.stock_critically_low': 'স্টক 10%-এর কম — 3 দিনে স্টকআউট ঝুঁকি',
  'anomaly.visit_gap_exceeded':   '3+ সপ্তাহে কোনো ভিজিট নেই — সক্রিয় ফসল মৌসুম',
  'anomaly.competitor_spotted':   'এই এলাকায় প্রতিযোগী কার্যকলাপ',
  'anomaly.complaint_unresolved': 'খোলা অভিযোগ — অবিলম্বে সমাধান দরকার',

  'priority.alert_one':           'সতর্কতা',
  'priority.alert_many':          'সতর্কতা',
  'override.complaint_immediate':   'খোলা অভিযোগ — অবিলম্বে ভিজিট প্রয়োজন',
  'override.pest_outbreak_region':  'এলাকায় গুরুতর কীট প্রকোপ',
  'override.visit_overdue_30':      'ভিজিট বাকি — 30+ দিন যোগাযোগ নেই',
  'trail.title':                'শেখার ইতিহাস',
  'trail.how_learns':           'মডেল কীভাবে শেখে',
  'trail.intro':                'প্রতিবার ফলাফল লগ হলে সিগন্যাল ওজন পুনঃগণনা হয়। এই ইতিহাস প্রতিটি সমন্বয় দেখায় — কোন সিগন্যাল গুরুত্ব পেল, কোনটি হারাল, এবং পরিবর্তনের কারণ কী ছিল।',
  'trail.back_to_overview':     '← সারসংক্ষেপে ফিরে যান',
  'trail.outcome_label':        'ফলাফল',
  'trail.logged_suffix':        'লগ হয়েছে',
  'trail.manual_recalibration': 'ম্যানুয়াল পুনঃসংযোজন',
  'trail.signals_shifted':      'সিগন্যাল পরিবর্তিত',
  'trail.what_changed':         'কী পরিবর্তিত হলো',
  'trail.all_weights':          'এই বিন্দুতে সব ওজন',
  'trail.empty':                'এখনো কোনো ওজন পরিবর্তন নেই।',

  'signal.pest_alert':          'কীট সতর্কতা',
  'signal.inventory_shortage':  'স্টকের ঘাটতি',
  'signal.days_since_visit':    'ভিজিটের পর দিন',
  'signal.weather_risk':        'আবহাওয়া ঝুঁকি',
  'signal.complaint_open':      'খোলা অভিযোগ',
  'signal.crop_stage':          'ফসল পর্যায়',
  'signal.revenue_potential':   'রাজস্ব সম্ভাবনা',
  'signal.competitor_activity': 'প্রতিযোগী কার্যকলাপ',
  'reason.ndvi_high_stress':     'উপগ্রহ ডেটা — গুরুতর ফসল চাপ',
  'reason.ndvi_moderate_stress': 'উপগ্রহ ডেটা — মাঝারি ফসল চাপ',
  'widget.satellite_title':    'উপগ্রহ ফসল স্বাস্থ্য',
  'widget.pest_title':         'আঞ্চলিক কীট পরামর্শ',
  'widget.scene_date':         'দৃশ্য তারিখ',
  'widget.cloud_cover':        'মেঘ আবরণ',
  'widget.source':             'উৎস',
  'widget.stress_score':       'চাপ স্কোর',
  'widget.severity':           'তীব্রতা',
  'widget.district':           'জেলা',
  'widget.live':               'লাইভ',
  'widget.baseline':           'বেসলাইন',
  'widget.unavailable':        'ডেটা উপলব্ধ নয়',
  'widget.loading':            'লোড হচ্ছে...',
  'auth.2fa.sent_to':       'যাচাইকরণ কোড পাঠানো হয়েছে',
  'auth.2fa.use_different':  'অন্য অ্যাকাউন্ট ব্যবহার করুন',
  'auth.2fa.enter_code':     '6-সংখ্যার কোড লিখুন',
  'auth.2fa.verify':         'যাচাই করুন ও সাইন ইন করুন',
  'auth.2fa.verifying':      'যাচাই করা হচ্ছে...',
  'auth.2fa.dev_hint':       'ডেভ মোড — কোড:',
}
const DICTIONARIES: Record<Lang, Record<string, string>> = { en, hi, gu, bn }
