"""
Top-level conftest for the backend test suite.

Placing this file at the backend root makes pytest automatically add the
backend directory to sys.path, so tests can `import core.x`, `import models.x`,
`import services.x` etc. without setup boilerplate in every test file.

Also defines shared fixtures used across the test suite:
  - test_db: in-memory SQLite with all tables created
  - client: FastAPI TestClient bound to that test DB
  - seeded_rep / seeded_manager: pre-created test accounts
"""
import os
import sys
import pytest
from pathlib import Path

# Ensure backend root is on sys.path. Belt-and-braces — pytest's rootdir
# discovery should already handle this since this file sits at backend root.
_BACKEND_ROOT = Path(__file__).parent
if str(_BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(_BACKEND_ROOT))

# Use a separate JWT secret + in-memory DB during tests so we can't accidentally
# clobber dev data, and so tokens generated by tests don't collide with real ones.
os.environ.setdefault("JWT_SECRET", "test-secret-do-not-use-in-prod")
os.environ.setdefault("JWT_REFRESH_SECRET", "test-refresh-secret-do-not-use-in-prod")
os.environ.setdefault("DEV_MODE", "true")
os.environ.setdefault("DATABASE_URL", "sqlite:///:memory:")

# Import these AFTER env vars are set
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from db.session import Base, get_db
from main import app

# Import every model so create_all() sees them
from models.db.rep import Rep
from models.db.auth_identity import AuthIdentity
from models.db.refresh_token import RefreshToken
from models.db.farmers import FarmerRetailer
from models.db.signal import Signal
from models.db.outcome import Outcome
from models.db.device import Device
from models.db.weight_history import WeightHistory
from models.db.email_verification import EmailVerification

@pytest.fixture(scope="function")
def test_db():
    """Fresh in-memory SQLite per test. Zero leakage between tests."""
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(bind=engine)
    TestSession = sessionmaker(bind=engine, autoflush=False, autocommit=False)

    def override_get_db():
        db = TestSession()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = override_get_db

    session = TestSession()
    try:
        yield session
    finally:
        session.close()
        Base.metadata.drop_all(bind=engine)
        app.dependency_overrides.clear()


@pytest.fixture(scope="function")
def client(test_db):
    """FastAPI TestClient wired to the in-memory test DB."""
    from fastapi.testclient import TestClient
    return TestClient(app)


@pytest.fixture(scope="function")
def seeded_rep(test_db):
    """Pre-create a rep account for login tests."""
    from services.auth_service import AuthService
    svc = AuthService()
    rep = svc.ensure_seed_rep(
        test_db,
        rep_id="REP_TEST",
        name="Test Rep",
        email="test.rep@syngenta.com",
        phone="9999999000",
        password="testpass123",
        role="rep",
    )
    return rep


@pytest.fixture(scope="function")
def seeded_manager(test_db):
    """Pre-create a manager account for permission tests."""
    from services.auth_service import AuthService
    svc = AuthService()
    mgr = svc.ensure_seed_rep(
        test_db,
        rep_id=None,
        name="Test Manager",
        email="test.manager@syngenta.com",
        phone="9999999001",
        password="mgrpass123",
        role="manager",
        managed_rep_ids=["REP_TEST"],
    )
    return mgr


@pytest.fixture(scope="function")
def auth_headers(client, seeded_rep):
    """Logged-in rep auth headers for protected endpoints.

    Handles both legacy single-factor login AND 2FA-required login. In tests
    DEV_MODE=true so the OTP comes back in the response body — we extract it
    and immediately POST to /2fa/verify to complete the flow.
    """
    res = client.post(
        "/auth/login/password",
        json={"identifier": "test.rep@syngenta.com", "password": "testpass123"},
    )
    assert res.status_code == 200, f"Login fixture failed: {res.text}"
    body = res.json()

    if body.get("requires_2fa"):
        # 2FA branch — complete the challenge
        challenge_id = body["challenge_id"]
        dev_otp = body["dev_otp"]
        assert dev_otp, "DEV_MODE should return dev_otp in test environment"
        verify_res = client.post(
            "/auth/2fa/verify",
            json={"challenge_id": challenge_id, "code": dev_otp},
        )
        assert verify_res.status_code == 200, f"2FA verify failed: {verify_res.text}"
        token = verify_res.json()["access_token"]
    else:
        # Legacy single-factor (role not in TWO_FA_REQUIRED_ROLES)
        token = body["access_token"]

    return {"Authorization": f"Bearer {token}"}